# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.

# Version of this configuration file's structure and semantics in AzureML.
# This directive is stored in a comment to preserve the Conda file structure.
# [AzureMlVersion] = 2

name: project_environment

channels:
  # Required for jasper
  - conda-forge

dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.5.2
  # Required for Jupyter Notebooks.
  - ipykernel=4.6.1
  # some ml packages
  - nltk
  - scikit-learn
  - lightgbm
  #- keras>=2.0.9
  - tensorflow-gpu
  # Required for CNTK 2.2
  #- libpng=1.2
  #- jasper

  - pip:
    # Required packages for AzureML execution, history, and data preparation.
    - --index-url https://azuremldownloads.azureedge.net/python-repository/preview
    - --extra-index-url https://pypi.python.org/simple
    - azureml-requirements
    - sacred
    - tqdm
    - tables
    - h5py
    #- lightgbm
    - pymongo
    # The API for Azure Machine Learning Model Management Service.
    # Details: https://github.com/Azure/Machine-Learning-Operationalization
    - azure-ml-api-sdk==0.1.0a10
    - azure-mgmt
    - keras>=2.1.5
    - python-telegram-bot
    - gensim>=3.3.0
    - translation>=1.0.5
    - langdetect>=1.0.7
