exec_params:
  cached_prefix: gru_glove
  debug_mode: false
  disable_cache: false
  num_folds: 5,
  retrain: true
  skip_cv: false
feature_params:
  embed_size: 300
  embedding_file: glove.6B.300d.txt
  max_features: 30000
  maxlen: 100
fit_params:
  batch_size: 64
  epochs: 10
  verbose: 2
model_params:
  dropout1: 0.4
  gru1: 60
  early_stop_patience: 2
  use_tensorboard: true
  tensorboard_hist_freq: 1
  tensorboard_write_graph: true
  tensorboard_write_grads: true
  tensorboard_embeddings_freq: 1
