exec_params:
  model_type: LGB
  cached_prefix: LGB
  debug_mode: false
  disable_cache: false
  num_folds: 5
  retrain: false
  skip_cv: false
feature_params:
  use_cnt_features: true
  charvec_params:
    max_features: 10000
    min_df: 3
    ngram_range: !!python/tuple [2, 6]
    strip_accents: unicode
    sublinear_tf: true
  wordvec_params:
    max_features: 10000
    min_df: 3
    ngram_range: !!python/tuple [1, 3]
    smooth_idf: 1
    strip_accents: unicode
    sublinear_tf: true
    token_pattern: \w{1,}
    use_idf: 1
fit_params:
  verbose_eval: 50
model_params:
  early_stop_lookup: {identity_hate: 30, insult: 30,
                      obscene: 30, severe_toxic: 30,
                      threat: 30, toxic: 30}
  lgb_params:
    application: binary
    bagging_fraction: 0.8
#    data_random_seed: 2
    feature_fraction: 0.4
    lambda_l1: 1
    lambda_l2: 1
    learning_rate: 0.15
    metric: auc
    #nthread: 4
    num_leaves: 61
    #min_data_in_leaf: 50
    verbosity: -1
  rounds_lookup: {identity_hate: 600, insult: 600, obscene: 600,
                  severe_toxic: 600, threat: 600, toxic: 600}
  selector_threshold: 0.2
  use_logreg_selector: false