exec_params:
  model_type: CNN
  cached_prefix: NN
  debug_mode: false
  disable_cache: false
  num_folds: 5,
  retrain: true
  skip_cv: false
feature_params:
  embed_size: 300
  #embedding_file: glove.twitter.27B.200d.txt
  max_features: 200000
  maxlen: 300
  preprocessing_params:
    remove_appo: true
    repl_smileys: true
fit_params:
  batch_size: 64
  epochs: 10
  verbose: 2
model_params:
  pretrained_embeddings: false
  cnn_filter_sizes: [128, 128, 128]
  cnn_kernel_sizes: [5,5,5]
  cnn_pooling_sizes: [5, 5, 40]
  dropout1: 0.3
  dense1: 128
  learning_rate: 0.00005
  early_stop_patience: 2
  use_tensorboard: false
  tensorboard_hist_freq: 0
  tensorboard_write_graph: false
  tensorboard_write_grads: false
  tensorboard_embeddings_freq: 0
