exec_params:
  cached_prefix: gru_glove
  debug_mode: false
  disable_cache: false
  num_folds: 5,
  retrain: true
  skip_cv: false
feature_params:
  embed_size: 300
  embedding_file: glove.840B.300d.txt
  max_features: 200000
  maxlen: 200
fit_params:
  batch_size: 32
  epochs: 10
  verbose: 2
model_params:
  dropout1: 0.5
  gru1: 60
  early_stop_patience: 2
  use_tensorboard: false
  tensorboard_hist_freq: 0
  tensorboard_write_graph: false
  tensorboard_write_grads: false
  tensorboard_embeddings_freq: 0
