exec_params:
  cached_prefix: gru_glove
  debug_mode: false
  disable_cache: false
  num_folds: 5,
  retrain: true
  skip_cv: false
feature_params:
  embed_size: 100
  embedding_file: glove.twitter.27B.100d.txt
  max_features: 100000
  maxlen: 150
fit_params:
  batch_size: 128
  epochs: 20
  verbose: 2
model_params:
  dropout1: 0.4
  gru1: 80
  early_stop_patience: 3
  use_tensorboard: false
  tensorboard_hist_freq: 0
  tensorboard_write_graph: false
  tensorboard_write_grads: false
  tensorboard_embeddings_freq: 0
