exec_params:
  model_type: LSTM
  cached_prefix: NN
  debug_mode: false
  disable_cache: false
  num_folds: 5,
  retrain: true
  skip_cv: false
feature_params:
  embed_size: 200
  embedding_file: glove.twitter.27B.200d.txt
  max_features: 100000
  maxlen: 200
  preprocessing_params:
    remove_appo: true
    repl_smileys: true
fit_params:
  batch_size: 64
  epochs: 10
  verbose: 2
model_params:
  pretrained_embeddings: true
  lstm1: 60
  dropout1: 0.2
  dropout2: 0.2
  dense1: 50
  optimizer: adam
  early_stop_patience: 2
  use_tensorboard: false
  tensorboard_hist_freq: 0
  tensorboard_write_graph: false
  tensorboard_write_grads: false
  tensorboard_embeddings_freq: 0
