exec_params:
  model_type: GRU
  cached_prefix: NN
  debug_mode: false
  disable_cache: false
  num_folds: 5,
  retrain: true
  skip_cv: false
feature_params:
  embed_size: 200
  embedding_file: glove.twitter.27B.200d.txt
  max_features: 150000
  maxlen: 250
  preprocessing_params:
    remove_appo: true
    repl_smileys: true
fit_params:
  batch_size: 128
  epochs: 20
  verbose: 3
model_params:
  pretrained_embeddings: true
  optimizer: nadam
  dropout1: 0.5
  gru1: 124
  early_stop_patience: 2
  additional_dense: true
  dense1: 300
  dropout2: 0.5
  use_tensorboard: false
  tensorboard_hist_freq: 0
  tensorboard_write_graph: false
  tensorboard_write_grads: false
  tensorboard_embeddings_freq: 0
